angular.module('MetronicApp').constant('REGEX_CEP', '\d{5}-\d{3}');
angular.module('MetronicApp').constant('REGEX_EMAIL', '/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/');
angular.module('MetronicApp').constant('LIMIT_UPLOAD_IMAGE', 5);
angular.module('MetronicApp').constant('UPLOAD_IMG_URL', 'rest/private/imagemanuncios/uploadimages');
angular.module('MetronicApp').constant('UPLOAD_IMG_PROFILE_URL', 'rest/private/imagemanuncios/uploadimage/profile');
angular.module('MetronicApp').constant('TABLE_LABELS', 'js/constantes/DataTables_PT-BR.json');
angular.module('MetronicApp').constant('JSON_ESTADOS', 'js/constantes/Estados.json');
angular.module('MetronicApp').constant('COOKIE_NAME', 'midia_ckie');
angular.module('MetronicApp').constant('TOKEN', 'token_kmedia');
angular.module('MetronicApp').constant('COOKIE_PTH_URL', 'midia/#!/');
angular.module('MetronicApp').constant('RECAPTCHA_PUB', '6LfgfhQTAAAAAP5UsUWzJYyHDA2v5viRQINrPxWC');
angular.module('MetronicApp').constant('CATEGORIAS_MAPPER', 'rest/categoria/');
angular.module('MetronicApp').constant('CATEGORIAS_MAPPER_JSON', 'rest/categoria/tiposmapper');
angular.module('MetronicApp').constant('FIPE_TIPO_JSON', 'https://fipeapi.appspot.com/api/1/[tipo]/marcas.json');
angular.module('MetronicApp').constant('FIPE_MODELO_JSON', 'https://fipeapi.appspot.com/api/1/[tipo]/veiculos/[idmarca].json');
angular.module('MetronicApp').constant('FIPE_ANO_JSON', 'https://fipeapi.appspot.com/api/1/[tipo]/veiculo/[idmarca]/[idmodelo].json');
angular.module('MetronicApp').constant('FIPE_PRECO_JSON', 'https://fipeapi.appspot.com/api/1/[tipo]/veiculo/[idmarca]/[idmodelo]/[idano].json');
angular.module('MetronicApp').constant('FIPE_TIPO_CARRO', 'CARRO');
angular.module('MetronicApp').constant('FIPE_TIPO_MOTO', 'MOTO');
angular.module('MetronicApp').constant('FIPE_TIPO_CAMINHOES', 'CAMINHAO');
angular.module('MetronicApp').constant('FIPE_TIPO_CARRO_REST', 'carros');
angular.module('MetronicApp').constant('FIPE_TIPO_MOTO_REST', 'motos');
angular.module('MetronicApp').constant('FIPE_TIPO_CAMINHOES_REST', 'caminhoes');

angular.module('MetronicApp').constant('ANUNCIO_TIPO_IMOV','IMOV');
angular.module('MetronicApp').constant('ANUNCIO_TIPO_AUTO','AUTO');
angular.module('MetronicApp').constant('ANUNCIO_TIPO_PROD','PROD');
angular.module('MetronicApp').constant('ANUNCIO_TIPO_SERV','SERV');
angular.module('MetronicApp').constant('ANUNCIO_TIPO_MOTOS','MOTO');
angular.module('MetronicApp').constant('ANUNCIO_TIPO_CARROS','CARRO');
angular.module('MetronicApp').constant('ANUNCIO_TIPO_CAMINHOES','CAMINHAO');
angular.module('MetronicApp').constant('ANUNCIO_TIPO_RESIDENCIAL','RESIDENC');
angular.module('MetronicApp').constant('ANUNCIO_TIPO_COMERCIAL','COMERC');
angular.module('MetronicApp').constant('ANUNCIO_TIPO_RURAL','RURAL');

